[package]
name = "ckv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-skiplist = "0.1"
bytes = "1"
thiserror = "1"
crc32fast = "1"
